<script setup lang="ts">
import {ref,watch} from 'vue';
import {BrowserClient,BrowserApiError,type BrowserActorContext} from '@fluctlight/browser-client';
import Button from '@/components/ui/button/Button.vue';
import { randomId } from '../../random-id';
import {apiOrigin} from '../../runtime-config';
const props=defineProps<{fluctlightId:string;actors:{id:string;label:string}[]}>();
const client=new BrowserClient(apiOrigin),target=ref(''),context=ref<BrowserActorContext|null>(null),busy=ref(false),error=ref(''),notice=ref(''),reason=ref('');
const draft=ref<Record<string,string>>({});const fields=[['name','显示身份'],['occupation','职业'],['background','背景'],['interests','稳定兴趣'],['preferences','偏好'],['location','粗粒度所在地（可未知）'],['location_scope','地点背景'],['timezone','IANA时区（可未知）']] as const;
let epoch=0;let pending:string|null=null;
async function load(keepDraft=false){const e=++epoch;busy.value=true;try{const value=await client.actorContext(props.fluctlightId,target.value);if(e!==epoch)return;context.value=value;if(!keepDraft){draft.value=Object.fromEntries(fields.map(([key])=>[key,String(value.background[key]??'')]));pending=null;}error.value='';}catch(c){if(e===epoch)error.value=String(c);}finally{if(e===epoch)busy.value=false;}}
async function save(){if(!context.value)return;const e=epoch;busy.value=true;pending??=randomId();try{const value=await client.updateActorContext(props.fluctlightId,target.value,{expectedContextVersion:context.value.context_version,idempotencyKey:pending!,operation:'change',reason:reason.value,background:Object.fromEntries(fields.map(([key])=>[key,draft.value[key]?.trim()||null]))});if(e!==epoch)return;context.value=value;pending=null;notice.value='背景已生效；相关目标与尚未启动的行动需要复核。配置修改不会被当作对方回应。';error.value='';}catch(c){if(e===epoch)error.value=c instanceof BrowserApiError&&c.status===409?'版本冲突，草稿已保留。请读取新版本后再保存。':String(c);}finally{if(e===epoch)busy.value=false;}}
watch(()=>props.fluctlightId,()=>{epoch++;context.value=null;target.value=props.actors[0]?.id??'';draft.value={};pending=null;notice.value='';},{immediate:true});
watch(()=>[props.fluctlightId,target.value],()=>{context.value=null;pending=null;notice.value='';if(target.value)void load();},{immediate:true});
watch(()=>props.actors,()=>{if(!target.value&&props.actors.length)target.value=props.actors[0]!.id;});
</script>
<template><section class="actor-context-editor" aria-label="Actor背景与配置修订"><h3>Actor背景与配置来源</h3><label>对象<select v-model="target"><option v-for="a in actors" :key="a.id" :value="a.id">{{a.label}}</option></select></label><p v-if="error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p><form v-if="context" @submit.prevent="save"><label v-for="[key,label] in fields" :key="key">{{label}}<input v-model="draft[key]" maxlength="1024" /></label><label>变更说明<input v-model="reason" required maxlength="1000" /></label><div><Button :disabled="busy||!reason.trim()">保存背景</Button><Button type="button" variant="outline" :disabled="busy" @click="load(true)">读取新版本并保留草稿</Button></div></form><details v-if="context"><summary>来源、版本与有效期</summary><p>配置版本 {{context.context_version}}</p><p v-for="f in context.history" :key="String(f.fact_id)">{{f.attribute}}：{{f.value}} · {{f.epistemic_kind}} · {{f.revision}} · {{f.effective_at}} – {{f.valid_until||'当前'}} · {{f.source_ref}}</p><h4>关系配置修订</h4><p v-for="r in context.relationship_history" :key="String(r.id)">{{r.created_at}} · 修订 {{r.revision}} · {{r.summary}}</p></details></section></template>
<style scoped>.actor-context-editor{display:grid;gap:12px;padding:16px;border:1px solid var(--surface-border);border-radius:16px;background:var(--surface-glass);min-width:0}form{display:grid;gap:12px;grid-template-columns:repeat(2,minmax(0,1fr))}label{display:grid;gap:6px}input,select{width:100%;padding:8px;border:1px solid var(--surface-border);border-radius:8px;box-sizing:border-box}p{overflow-wrap:anywhere}form div{display:flex;flex-wrap:wrap;gap:8px}@media(max-width:640px){form{grid-template-columns:minmax(0,1fr)}}.actor-context-editor :deep(.bg-primary) { color: var(--primary-foreground); }
</style>
