<script setup lang="ts">
import { onMounted, ref } from "vue";

import { useConversationStore } from "../stores/conversations";
import { useControlCenterStore } from "../stores/control-center";

const emit = defineEmits<{ diagnostics: []; logout: [] }>();
const store = useConversationStore();
const controlCenter = useControlCenterStore();

const providerRoles = [
  { value: "initialization", label: "初始化" }, { value: "cognitive_assessment", label: "认知判断" }, { value: "action_realization", label: "回复生成" }, { value: "reflection", label: "反思" }, { value: "embedding", label: "Embedding" }, { value: "media_prompt", label: "媒体提示词" },
] as const;
const selectedProviderRole = ref<(typeof providerRoles)[number]["value"]>("cognitive_assessment");
const roleEndpointId = ref(""); const roleModelId = ref(""); const roleTokenBudget = ref(2048); const roleTimeoutSeconds = ref(60);
const endpointPickerId = ref(""); const endpointId = ref("primary"); const endpointUrl = ref(""); const endpointSecret = ref(""); const providerKind = ref("openai-compatible");
const comfyUiUrl = ref(""); const comfyUiWorkflow = ref(""); const changedOwnerPassword = ref("");

function selectEndpoint(id: string) { endpointPickerId.value = id; const endpoint = controlCenter.providerEndpoints.find((item) => item.id === id); if (!endpoint) return; endpointId.value = endpoint.id; endpointUrl.value = endpoint.base_url; providerKind.value = endpoint.kind; endpointSecret.value = ""; }
async function selectRole(role: (typeof providerRoles)[number]["value"]) { selectedProviderRole.value = role; const binding = controlCenter.providerBindings.find((item) => item.role === role); roleEndpointId.value = binding?.endpoint_id ?? controlCenter.providerEndpoints.find((item) => item.id === "primary")?.id ?? controlCenter.providerEndpoints[0]?.id ?? ""; roleModelId.value = binding?.model_id ?? ""; roleTokenBudget.value = binding?.token_budget ?? 2048; roleTimeoutSeconds.value = binding?.timeout_seconds ?? 60; await controlCenter.loadProviderModels(roleEndpointId.value); }
async function load() { await controlCenter.loadSettings(); const primary = controlCenter.providerEndpoints.find((endpoint) => endpoint.id === "primary")?.id ?? controlCenter.providerEndpoints[0]?.id ?? ""; selectEndpoint(primary); await selectRole(selectedProviderRole.value); const comfy = controlCenter.settings?.values["media.comfyui"]; if (comfy && typeof comfy === "object" && !Array.isArray(comfy)) { comfyUiUrl.value = String((comfy as Record<string, unknown>).baseUrl ?? ""); const workflow = (comfy as Record<string, unknown>).workflow; comfyUiWorkflow.value = workflow && typeof workflow === "object" ? JSON.stringify(workflow, null, 2) : ""; } const autonomy = controlCenter.settings?.values["product.autonomy"]; const retention = controlCenter.settings?.values["diagnostics.retention"]; controlCenter.autonomySettingsJson = JSON.stringify(autonomy && typeof autonomy === "object" && !Array.isArray(autonomy) ? autonomy : { mode: "active", allowed_actions: ["proactive_message", "memory_candidate", "relationship_candidate", "schedule_proposal", "media_request", "moment"], budget_remaining: 1 }, null, 2); controlCenter.diagnosticsRetentionJson = JSON.stringify(retention && typeof retention === "object" && !Array.isArray(retention) ? retention : { retention_days: 30, max_rows: 10000 }, null, 2); }
async function saveRole() { if (!roleEndpointId.value || !roleModelId.value.trim()) { controlCenter.error = "请为该模型角色选择 endpoint 和模型。"; return; } await controlCenter.configureModelRole({ role: selectedProviderRole.value, endpointId: roleEndpointId.value, modelId: roleModelId.value.trim(), tokenBudget: roleTokenBudget.value, timeoutSeconds: roleTimeoutSeconds.value }); if (!controlCenter.error) await selectRole(selectedProviderRole.value); }
async function saveEndpoint() { if (!endpointId.value.trim() || !endpointUrl.value.trim()) { controlCenter.error = "请完整填写 endpoint 标识和服务地址。"; return; } if (endpointSecret.value) { await controlCenter.saveSettings({}, { [`provider:${endpointId.value.trim()}`]: endpointSecret.value }); if (controlCenter.error) return; } await controlCenter.configureProviderEndpoint({ endpointId: endpointId.value.trim(), kind: providerKind.value, baseUrl: endpointUrl.value.trim(), secretPurpose: `provider:${endpointId.value.trim()}` }); if (!controlCenter.error) { endpointSecret.value = ""; selectEndpoint(endpointId.value.trim()); await selectRole(selectedProviderRole.value); } }
async function saveMedia() { if (!comfyUiUrl.value.trim() || !comfyUiWorkflow.value.trim()) { if (comfyUiUrl.value.trim() || comfyUiWorkflow.value.trim()) controlCenter.error = "请同时填写 ComfyUI URL 和图片工作流。"; return; } try { const workflow = JSON.parse(comfyUiWorkflow.value); if (!workflow || typeof workflow !== "object" || Array.isArray(workflow)) throw new Error("workflow_not_object"); await controlCenter.saveSettings({ "media.comfyui": { baseUrl: comfyUiUrl.value.trim(), workflow } }); } catch { controlCenter.error = "ComfyUI 图片工作流必须是 JSON 对象。"; } }
async function changePassword() { const changed = await store.changePassword(changedOwnerPassword.value); if (changed) changedOwnerPassword.value = ""; }
onMounted(() => void load());
</script>

<template>
  <section class="page settings-page" aria-labelledby="settings-title">
    <header class="page-header"><div><p class="eyebrow">SYSTEM</p><h1 id="settings-title">设置</h1><p class="page-lede">配置模型、媒体和运行策略。敏感密钥只写入，不会再次显示。</p></div><div class="header-actions"><span class="status-pill"><i class="status-dot" />{{ store.sending ? "正在思考" : "系统就绪" }}</span><button class="secondary-button" type="button" @click="emit('diagnostics')">诊断中心</button><button class="secondary-button" type="button" @click="emit('logout')">退出登录</button></div></header>
    <p v-if="controlCenter.error" class="error-banner" role="alert">{{ controlCenter.error }}</p>
    <section class="settings-section" aria-labelledby="model-role-title"><div class="section-heading"><div><p class="eyebrow">MODEL ROLES</p><h2 id="model-role-title">模型角色绑定</h2></div></div><div class="segmented-control" role="tablist" aria-label="模型角色"><button v-for="providerRole in providerRoles" :key="providerRole.value" class="segment-button" :class="{ selected: selectedProviderRole === providerRole.value }" type="button" role="tab" :aria-selected="selectedProviderRole === providerRole.value" @click="selectRole(providerRole.value)">{{ providerRole.label }}</button></div><form class="stack-form" @submit.prevent="saveRole"><div class="form-grid"><label for="role-endpoint">使用 Endpoint<select id="role-endpoint" v-model="roleEndpointId" @change="controlCenter.loadProviderModels(roleEndpointId)"><option value="" disabled>请选择 endpoint</option><option v-for="endpoint in controlCenter.providerEndpoints" :key="endpoint.id" :value="endpoint.id">{{ endpoint.id }} · {{ endpoint.base_url }}</option></select></label><label for="role-model">模型 ID<input id="role-model" v-model="roleModelId" type="text" maxlength="256" placeholder="模型标识" /></label><label for="role-budget">Token 预算<input id="role-budget" v-model.number="roleTokenBudget" type="number" min="1" step="1" /></label><label for="role-timeout">超时（秒）<input id="role-timeout" v-model.number="roleTimeoutSeconds" type="number" min="1" step="1" /></label></div><p class="field-note">{{ controlCenter.providerModelsError || (controlCenter.providerModels.length ? "模型列表已从 endpoint 读取。" : "该 endpoint 尚未返回模型列表，可手动填写模型 ID。") }}</p><button class="primary-button" type="submit" :disabled="controlCenter.saving">{{ controlCenter.saving ? "正在保存..." : "保存当前角色绑定" }}</button></form></section>
    <section class="settings-section" aria-labelledby="endpoint-title"><div class="section-heading"><div><p class="eyebrow">ENDPOINTS</p><h2 id="endpoint-title">模型 Endpoint</h2></div></div><form class="stack-form" @submit.prevent="saveEndpoint"><label for="endpoint-picker">已保存 Endpoint<select id="endpoint-picker" v-model="endpointPickerId" @change="selectEndpoint(endpointPickerId)"><option value="">新建或手动编辑</option><option v-for="endpoint in controlCenter.providerEndpoints" :key="endpoint.id" :value="endpoint.id">{{ endpoint.id }} · {{ endpoint.base_url }}</option></select></label><div class="form-grid"><label for="endpoint-id">Endpoint 标识<input id="endpoint-id" v-model="endpointId" maxlength="128" /></label><label for="provider-kind">协议类型<input id="provider-kind" v-model="providerKind" maxlength="64" /></label><label for="endpoint-url">服务地址<input id="endpoint-url" v-model="endpointUrl" type="url" placeholder="http://host:port/v1" /></label><label for="endpoint-secret">访问密钥<input id="endpoint-secret" v-model="endpointSecret" type="password" autocomplete="new-password" placeholder="仅写入，不会再次显示" /></label></div><p class="field-note">保存 endpoint 会解除其模型角色绑定；API Key 仅写入，不会返回浏览器。</p><button class="primary-button" type="submit" :disabled="controlCenter.saving">{{ controlCenter.saving ? "正在保存..." : "保存 Endpoint" }}</button></form><div class="binding-list"><h3>当前模型角色绑定</h3><p v-if="!controlCenter.providerBindings.length" class="field-note">尚未启用任何模型角色。</p><div v-for="binding in controlCenter.providerBindings" :key="binding.role" class="binding-row"><strong>{{ providerRoles.find((role) => role.value === binding.role)?.label ?? binding.role }}</strong><span>{{ binding.model_id }}</span><small>{{ binding.endpoint_id }} · {{ binding.endpoint_status }} · {{ binding.token_budget }} Token / {{ binding.timeout_seconds }} 秒</small></div></div></section>
    <section class="settings-section" aria-labelledby="media-title"><div class="section-heading"><div><p class="eyebrow">MEDIA PROVIDER</p><h2 id="media-title">ComfyUI</h2></div></div><form class="stack-form" @submit.prevent="saveMedia"><label for="comfy-url">ComfyUI URL<input id="comfy-url" v-model="comfyUiUrl" type="url" placeholder="http://comfyui:8188" /></label><label for="comfy-workflow">图片工作流<textarea id="comfy-workflow" v-model="comfyUiWorkflow" rows="7" spellcheck="false" placeholder='{"node":{"inputs":{"text":"{{prompt}}"}}}' /></label><button class="primary-button" type="submit" :disabled="controlCenter.saving">保存媒体设置</button></form></section>
    <section class="settings-section" aria-labelledby="operations-title"><div class="section-heading"><div><p class="eyebrow">AUTONOMY / DIAGNOSTICS</p><h2 id="operations-title">运行策略</h2></div></div><form class="stack-form" @submit.prevent="controlCenter.saveOperationalSettings"><label for="autonomy-json">自治策略<textarea id="autonomy-json" v-model="controlCenter.autonomySettingsJson" rows="5" spellcheck="false" /></label><label for="retention-json">诊断保留策略<textarea id="retention-json" v-model="controlCenter.diagnosticsRetentionJson" rows="4" spellcheck="false" /></label><button class="primary-button" type="submit" :disabled="controlCenter.saving">保存运行策略</button></form></section>
    <section class="settings-section" aria-labelledby="owner-title"><div class="section-heading"><div><p class="eyebrow">OWNER</p><h2 id="owner-title">所有者</h2></div></div><form class="stack-form" @submit.prevent="changePassword"><label for="owner-password">新密码<input id="owner-password" v-model="changedOwnerPassword" type="password" autocomplete="new-password" minlength="6" required aria-describedby="owner-password-requirements" /></label><p id="owner-password-requirements" class="field-note">新密码至少 6 个字符。修改后会撤销当前所有会话。</p><p v-if="store.authError" class="error-banner" role="alert">{{ store.authError }}</p><button class="primary-button" type="submit" :disabled="store.authLoading || !changedOwnerPassword">{{ store.authLoading ? "正在修改..." : "修改密码" }}</button></form></section>
  </section>
</template>
